apiVersion: batch/v1
kind: Job
metadata:
  name: content-creator
spec:
  template:
    spec:
      containers:
      - name: content-creator
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo '<!DOCTYPE html>
          <html>
          <head>
            <title>LSC Lab 6 Web</title>
          </head>
          <body>
            <div class="container">
              <h1>Hello World!!</h1>
              <p>This is a simple web page created by a Kubernetes Job.</p>
            </div>
          </body>
          </html>' > /mnt/data/index.html
        volumeMounts:
        - name: web-content
          mountPath: /mnt/data
      restartPolicy: Never
      volumes:
      - name: web-content
        persistentVolumeClaim:
          claimName: web-content-pvc
  backoffLimit: 4